services:
  portal:
    build: .
    ports:
      - "5000:5000"
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy=*
      - TZ=Asia/Damascus
    volumes:
      - ./data:/app/data
    restart: unless-stopped

